engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  pep8:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.py"
exclude_paths:
- "**/migrations/*"
- "**/docs/*"
